name: Build Docs

on: 
  push:
    branches: 
      - master

jobs:
    build:
        runs-on: windows-latest
        
        steps:
        - uses: actions/checkout@v2

        - name: Build the docs
          shell: cmd
          working-directory: ./
          run: '"./docfx/2.58/docfx.exe" docfx.json'

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./_site
